project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

pull_request_title: Translation updates from Crowdin
pull_request_labels: [ crowdin ]

commit_message: "[skip ci]"

files:
  - source: /extension/en/messages.json
    translation: /extension/%two_letters_code%/messages.json
    skip_untranslated_strings: true
    type: chrome

  - source: /native/en-US/**/*.ftl
    dest: /native/en-US/**/%file_name%.ftl
    translation: /native/%two_letters_code%/**/%original_file_name%
    type: ftl
